name: dart_etcd
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: liang <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
#  path: ^1.4.1
  protobuf: ^0.7.1
  grpc: ^0.3.1

dev_dependencies:
  test: ^0.12.0
